language: php

php:
#  - '5.4'
#  - '5.5'
#  - '5.6'
#  - '7.0'
  - '7.1'
#  - nightly

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

install:
  - composer install --no-interaction

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: vendor/bin/phpunit
